### ISSUE TITLE
Scroll history seems to apply to chats outside of the one you have selected

### ISSUE THREAD

**Issue by CSab6482** [open-imcore/imcore.react#1]
> I currently have the scrolling set to the default natural scrolling. The bug is that I scroll up in a chat, and then I switch to another chat, but instead of being brought to the bottom of the newly selected chat, I am also scrolled up there. This doesn't happen every time. Below is a video of what I'm talking about.
> 
> https://user-images.githubusercontent.com/53708281/112708836-d976ba80-8e8a-11eb-83c9-0e86d87c5ec3.mp4

This is probably an issue with the frontend, not the server. My bad.

**Comment by EricRabil** [comment]
Fixed by 0a6b9de
