### ISSUE TITLE
[Bug] When using iOS as a server, Twitter web previews are unreadable in dark mode

### ISSUE THREAD

**Issue by CSab6482** [open-imcore/imcore.react#19]
I already reported this in the Discord, but I wanted to open a ticket just in case. Eric originally commented

> it sources from the color scheme on your device, on mac im able to force it to run in light mode but i didnt take ios into account. i will make a patch

Below are screenshots of the same link when my device is in both light and dark mode
![Light Mode](https://user-images.githubusercontent.com/53708281/114121255-0b8d1100-98bc-11eb-9fd3-d37bf8f2de40.png)
![Dark Mode](https://user-images.githubusercontent.com/53708281/114121259-0cbe3e00-98bc-11eb-9250-1f579800b6c9.png)

**Comment by CSab6482** [comment]
Also, another note on this, is the patch going to force light mode at all times? And then later, when dark mode is supported, this patch will be undone?

**Comment by EricRabil** [comment]
My fix for this will be to provide colors for both light and dark mode, and allow the client to decide which colors to use. Forced light mode will be killed.

**Comment by CSab6482** [comment]
[Done](https://github.com/open-imcore/imessage-rest/issues/22) 👍
