### ISSUE TITLE
[Feature Request] - Have the currently selected chat show up as another color in the chat history list on the left

### ISSUE THREAD

**Issue by CSab6482** [open-imcore/imcore.react#2]
On macOS, this is blue when the Messages app is focused and light gray when it isn't focused, and on iOS it's always light gray. I prefer the blue, but either would be good.

**Comment by EricRabil** [comment]
I'll add this in the next round of commits

**Comment by CSab6482** [comment]
Closed with https://github.com/open-imcore/imcore.react/tree/3d1aa7743e30d5ef6cdc227b34c04643c1a50b14

**Comment by CSab6482** [comment]
Reopening because this feature is a bit finnicky with the newly implemented search feature
![image](https://user-images.githubusercontent.com/53708281/114336453-024eaf00-9b1d-11eb-9dd0-c619f650d115.png)

**Comment by EricRabil** [comment]
Thanks, I’ll disable active chat indicator when in search mode

-- Eric Rabil ( ***@***.*** )

Sent via Superhuman iOS ( ***@***.*** )

**Comment by CSab6482** [comment]
To add to this, searching and then exiting causes chat histories to overlap. I took a video of it but unfortunately it doesn't show with privacy mode turned on. I have a zoomed in screenshot of one overlapped chat box below the video.

https://user-images.githubusercontent.com/53708281/114440636-5f3b7b00-9b98-11eb-8cf1-915a0d823d58.mp4

![image](https://user-images.githubusercontent.com/53708281/114439996-a07f5b00-9b97-11eb-9b46-457e50e5d954.png)

**Comment by CSab6482** [comment]
As far as I can tell, all of these issues have been fixed as of https://github.com/open-imcore/imcore.react/tree/b8c633e8d7a86e94a8180e313ce4a33dd62df7ce
