### ISSUE TITLE
[Feature Request] Display attachments at a smaller size

### ISSUE THREAD

**Issue by CSab6482** [open-imcore/imcore.react#21]
Like issue #19, this one comes from discord. This is mainly a problem when someone sends me many attachments (10+) and I want to look through all of them to get a general idea of the pictures. Because the photos are so big, it takes a while to scroll through them, and I can only show about one photo on my screen at a time (when they're vertical, anyways).

Below I have screenshots from macOS, iOS (in landscape mode), SMServer, MyMessage, and WebMessage. All of the apps were in full screen mode. I wrote down what percentage of horizontal space the same vertical photo took up on all of those frontends, and the average between iOS and macOS is 36.27%. SMServer is relatively close to this percentage, with WebMessage being lower and MyMessage being higher.
![macOS sample](https://user-images.githubusercontent.com/53708281/114122714-df26c400-98be-11eb-8ec9-50dfdd4186d0.png)
![iOS sample](https://user-images.githubusercontent.com/53708281/114122717-e057f100-98be-11eb-9a39-52ad2cecae50.png)
![SMServer sample](https://user-images.githubusercontent.com/53708281/114122720-e1891e00-98be-11eb-8330-9c021e2bfd90.png)
![MyMessage sample](https://user-images.githubusercontent.com/53708281/114122725-e3eb7800-98be-11eb-96e5-c6f1f130d12e.png)
![WebMessage sample](https://user-images.githubusercontent.com/53708281/114122727-e51ca500-98be-11eb-8465-4a8cfb105335.png)
Another (kind of) similar comment is that while attachments display at a larger size than on the host OS, link previews appear to load very true to size.

**Comment by CSab6482** [comment]
Below, I've attached a video of me scrolling from a web preview to a photo in MyMessage. The photo is much larger and I have to do a few scrolls before I can get to the bottom of it. The screenshot is from my iPad and shows the scaling on iOS. I drew over it in MSPaint to cover personal information, but I left the size of both attachments exactly the same.

https://user-images.githubusercontent.com/53708281/114277528-90ca1000-99f9-11eb-8b2f-7d25e1f60931.mp4

![PNG image](https://user-images.githubusercontent.com/53708281/114277535-94f62d80-99f9-11eb-95dc-5427414e0258.png)

**Comment by sabogalc** [comment]
https://github.com/open-imcore/imcore.react/pull/55
