### ISSUE TITLE
[(Dark mode) Bug] Emoji only texts do not have transparent backgrounds

### ISSUE THREAD

**Issue by CSab6482** [open-imcore/imcore.react#31]
![Emoji Background](https://user-images.githubusercontent.com/53708281/115171859-008f6900-a092-11eb-97ba-97cc2ebd9705.png)
![Emoji Background Sent](https://user-images.githubusercontent.com/53708281/115171861-02592c80-a092-11eb-902b-cd144499fb07.png)

**Comment by CSab6482** [comment]
One unintended consequence of this bug is that it partially "fixes" this part of [issue #6](https://github.com/open-imcore/imcore.react/issues/6#issuecomment-812651138)
![image](https://user-images.githubusercontent.com/53708281/115492680-3e29f880-a230-11eb-83d6-10cfb89a3838.png)

**Comment by sabogalc** [comment]
https://github.com/open-imcore/imcore.react/pull/53
