### ISSUE TITLE
[(Dark mode) Bug] The "To" text is black and hard to see

### ISSUE THREAD

**Issue by CSab6482** [open-imcore/imcore.react#32]
I'm not sure how it is on macOS, but I made a mockup based on how it looks on iOS (I copied the color from the "Search" text)
![How it is](https://user-images.githubusercontent.com/53708281/115171936-303e7100-a092-11eb-9cc5-1474ffb9d6df.png)
![How it should be](https://user-images.githubusercontent.com/53708281/115171939-32083480-a092-11eb-8d4f-ad1f2d83dcd3.png)

**Comment by sabogalc** [comment]
Similar to how I said in issue #43, this can be fixed by changing line [16](https://github.com/open-imcore/imcore.react/blob/master/src/styles/toolbar/_transcript-toolbar.scss#L16) of _transcript-toolbar.scss from `rgba(0, 0, 0, 0.6)` to `rgba(157, 157, 157, 1)`

**Comment by sabogalc** [comment]
I tried fixing this but unfortunately my changes didn't work
![image](https://user-images.githubusercontent.com/53708281/123691273-6848f980-d823-11eb-980a-9b11cd817a38.png)

**Comment by sabogalc** [comment]
https://github.com/open-imcore/imcore.react/pull/44
