### ISSUE TITLE
[(Dark mode) Bug] Some acknowledgements match the background color and appear transparent

### ISSUE THREAD

**Issue by CSab6482** [open-imcore/imcore.react#33]
I'm not sure if this bug is exclusive to images/attachments. It was also a tapback that I sent, so that might play a role too.
![Dark mode acknowledgement](https://user-images.githubusercontent.com/53708281/115315732-f0d15c80-a145-11eb-8641-0fa8c4b846b7.png)

**Comment by sabogalc** [comment]
I think this might've been fixed with [this pull request](https://github.com/open-imcore/imcore.react/pull/56). Closing for now.
