### ISSUE TITLE
[(Dark mode) Bug] Text caption under an attachment goes transparent sometimes depending on where you're scrolled

### ISSUE THREAD

**Issue by CSab6482** [open-imcore/imcore.react#35]
I wasn't really sure what to title this one

https://user-images.githubusercontent.com/53708281/115492443-d4115380-a22f-11eb-8c61-547c658bd879.mp4

**Comment by CSab6482** [comment]
Update - It looks like this isn't exclusive to videos. Images seem to be affected too.
![image](https://user-images.githubusercontent.com/53708281/115492549-f73c0300-a22f-11eb-89bf-af79d86495b2.png)

**Comment by sabogalc** [comment]
https://github.com/open-imcore/imcore.react/pull/54
