### ISSUE TITLE
[Bug] 20th chat and below do not show any text in the conversation preview (Needs Zoom for diagnosis/fix)

### ISSUE THREAD

**Issue by CSab6482** [open-imcore/imcore.react#4]
![20](https://user-images.githubusercontent.com/53708281/113338353-00a01280-92f7-11eb-8ed8-955048124c17.png)

**Comment by EricRabil** [comment]
Is there a significant gap in the timestamps that MyMessage shows for the 20th and below chat?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: CSab6482 ***@***.***>
Sent: Thursday, April 1, 2021 2:32:09 PM
To: open-imcore/imcore.react ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [open-imcore/imcore.react] [Bug] 20th chat and below do not show any text in the conversation preview (#4)


[20]<https://user-images.githubusercontent.com/53708281/113338353-00a01280-92f7-11eb-8ed8-955048124c17.png>

**Comment by CSab6482** [comment]
No, but the number 20 is consistent. My 20th chat from yesterday is not the same one from yesterday, but the blank messages still happen at the 20 mark for me. There's about 11 hours difference between chat 19 and chat 20

**Comment by CSab6482** [comment]
I think this issue is caused by a bugged attachment in the chat where this bug begins. The attachment is a video that is hard to get the video controls to show up on and that doesn't go black when I turn on privacy mode.

**Comment by CSab6482** [comment]
I'm not sure if it will help, but here is the message information of the bugged attachment
[Bugged video.txt](https://github.com/open-imcore/imcore.react/files/6290375/Bugged.video.txt)

**Comment by EricRabil** [comment]
Will reach out to schedule a zoom call soon, but I think this is a server-side issue.

**Comment by sabogalc** [comment]
This bug seemingly fixed itself I guess so that's pretty cool
![image](https://user-images.githubusercontent.com/53708281/123721601-ac082700-d854-11eb-910d-777834606434.png)
